#port: 8080
#downloadPath: /downloads
#"--driver", "/usr/local/bin/yt-dlp"
#downloaderPath: /usr/bin/yt-dlp
twitch:
  check_interval: 5s
# Optional settings 
require_auth: true
username: sf369
password: cricket321
queue_size: 4
